Update configvlan with shared subroutines

diff --git a/xCAT/postscripts/confignetwork b/xCAT/postscripts/confignetwork
--- a/xCAT/postscripts/confignetwork
+++ b/xCAT/postscripts/confignetwork
@@ -576,9 +576,13 @@ function configure_nicdevice {
             fi
             ipaddrs=$(find_nic_ips $nic_dev)
             if [ "$networkmanager_active" = "0" ]; then
-                create_vlan_interface ifname=$vlanname vlanid=$vlanid ipaddrs=$ipaddrs
+                create_vlan_interface ifname=$vlanname vlanid=$vlanid
             elif [ "$networkmanager_active" = "1" ]; then
                 create_vlan_interface_nmcli ifname=$vlanname vlanid=$vlanid ipaddrs=$ipaddrs
+            fi
+            if [ $? -ne 0 ]; then
+                log_error "configvlan failed."
+                errorcode=1
             fi
         #configure bond
         elif [ x"$nic_dev_type" = "xbond" ]; then
