enhanced

diff --git a/xCAT/postscripts/configeth b/xCAT/postscripts/configeth
--- a/xCAT/postscripts/configeth
+++ b/xCAT/postscripts/configeth
@@ -9,6 +9,15 @@ if [ "$(uname -s|tr 'A-Z' 'a-z')" = "linux" ];then
    . $str_dir_name/nicutils.sh
 fi
 error_code=0
+#########################################################################
+# ifdown/ifup will not be executed in diskful provision postscripts stage
+#########################################################################
+reboot_nic_bool=1
+if [ -z "$UPDATENODE" ] || [ $UPDATENODE -ne 1 ] ; then
+    if [ "$NODESETSTATE" = "install" ] && ! grep "REBOOT=TRUE" /opt/xcat/xcatinfo >/dev/null 2>&1; then
+        reboot_nic_bool=0
+    fi
+fi
 function configipv4(){
     str_if_name=$1
     str_v4ip=$2
@@ -404,9 +413,9 @@ if [ "$1" = "-r" ];then
         ip link show $str_nic_name | grep -i ',up'
         if [ $? -eq 0 ];then
             if [ "$str_os_type" = "debian" ];then
-                ip link set $str_nic_name down
+                ifdown --force $str_nic_name
             else
-                ip link set $str_nic_name down
+                ifdown $str_nic_name
             fi
         fi
 
@@ -641,7 +650,7 @@ elif [ "$1" = "-s" ];then
     fi
 
     if [ "$UPDATENODE" = "1" ] || grep "REBOOT=TRUE" /opt/xcat/xcatinfo >/dev/null 2>&1; then
-        ip link set $str_inst_nic down;ip link set $str_inst_nic up
+        ifdown $str_inst_nic;ifup $str_inst_nic
     fi 
     if [ $? -ne 0 ]; then
         log_error "ifup $str_inst_nic failed."
@@ -976,9 +985,11 @@ else
         if [ $bool_restart_flag -eq 1 ];then
             if [ "$str_nic_status" = "up" ];then
                 if [ "$str_os_type" = "debian" ];then
-                    ip link set $str_nic_name down > /dev/null
+                    ifdown --force $str_nic_name > /dev/null
                 else
-                    ip link set $str_nic_name down > /dev/null
+                    if [ $reboot_nic_bool ]; then
+                        ifdown $str_nic_name > /dev/null
+                    fi
                 fi
             fi
             #delete all old ip address
@@ -1057,11 +1068,13 @@ else
                 error_code=1
             fi
         else
-            echo "bring up ip"
-            ifup $str_nic_name
-            if [ $? -ne 0 ]; then
-                log_error "ifup $str_nic_name failed."
-                error_code=1
+            if [ $reboot_nic_bool ]; then
+                echo "bring up ip"
+                ifup $str_nic_name
+                if [ $? -ne 0 ]; then
+                    log_error "ifup $str_nic_name failed."
+                    error_code=1
+                fi
             fi
         fi
     fi
