Enhance autotest confignetwork related failure

diff --git a/xCAT/postscripts/confignetwork b/xCAT/postscripts/confignetwork
--- a/xCAT/postscripts/confignetwork
+++ b/xCAT/postscripts/confignetwork
@@ -328,13 +328,17 @@ function sort_nics_device_order {
                     else
                         ib_slots=$ib_slots,$alonenic
                     fi
+                elif [ x"$alonenictype" = "xvlan" ] || [ x"$alonenictype" = "bond" ]; then
+                    echo "Error: should configure nicdevices for $alonenic."
+                    errorcode=1
+                     
                 else
                     echo $alonenic
                 fi
             else
                 errorcode=1
                 echo "Error: nicips,nictypes and nicnetworks should be configured in nics table for $alonenic."
-                ((num1+=1)) 
+                ((num1+=1))
                 continue
             fi
         fi
@@ -530,8 +534,12 @@ function configure_nicdevice {
         #linux bridge type is bridge
         #openvswitch bridge type is bridge_ovs
         elif [ x"$nic_dev_type" = "xbridge_ovs" -o x"$nic_dev_type" = "xbridge" ]; then
-            create_bridge_interface ifname=$nic_dev _brtype=$nic_dev_type _port=$base_nic_dev _pretype=$base_nic_type
-     
+            check_brctl $nic_dev_type
+            if [ $? -ne 0 ]; then
+                errorcode=1
+            else
+               create_bridge_interface ifname=$nic_dev _brtype=$nic_dev_type _port=$base_nic_dev _pretype=$base_nic_type
+            fi
         #configure vlan 
         elif [ x"$nic_dev_type" = "xvlan" ]; then
             if echo "$nic_dev" | grep -sq ".*\.[0-9]\+"; then
