Bug Fix (3215493)
git-svn-id: https://svn.code.sf.net/p/xcat/code/xcat-core/trunk@9609 8638fb3e-16cb-4fca-ae20-7b5d299a9bcd

diff --git a/xCAT/postscripts/xcatdsklspost b/xCAT/postscripts/xcatdsklspost
--- a/xCAT/postscripts/xcatdsklspost
+++ b/xCAT/postscripts/xcatdsklspost
@@ -14,6 +14,21 @@
 #      update security  --> xcatdsklspost 5 -m/-M ...
 #
 #####################################################
+
+update_VPD()
+{
+    which vpdupdate > /dev/null
+
+    if [ $? -ne 0 ];then
+        echo "Command vpdupdate not found, VPD database won't be updated"
+		logger -t xCAT "xcatdsklspost: Command vpdupdate not found, VPD database won't be updated"
+    else
+        vpdupdate
+		logger -t xCAT "xcatdsklspost: updating VPD database"
+    fi
+}
+update_VPD
+
 download_postscripts()
 {
     server=$1
