Make sure SOL is set to the current active channel for that channels SOL config (necessary when the settings aren't *really* per-channel, but not smart enough to follow automatically)
git-svn-id: https://svn.code.sf.net/p/xcat/code/xcat-core/trunk@8974 8638fb3e-16cb-4fca-ae20-7b5d299a9bcd

diff --git a/xCAT-nbroot/overlay/bin/bmcsetup b/xCAT-nbroot/overlay/bin/bmcsetup
--- a/xCAT-nbroot/overlay/bin/bmcsetup
+++ b/xCAT-nbroot/overlay/bin/bmcsetup
@@ -223,6 +223,13 @@ if [ ! "$IPMIVER" == "1.5"  ]; then
         if [ $TRIES -gt $TIMEOUT ]; then break; fi
     done
     if [ $TRIES -gt $TIMEOUT ]; then echo "ERROR"; else echo "OK"; fi
+    echo -n "Putting SOL on channel $LANCHAN:"
+    while ! ipmitool raw 0xc 0x21 $LANCHAN 7 $LANCHAN > /dev/null; do
+        sleep 1
+        let TRIES=TRIES+1
+        if [ $TRIES -gt $TIMEOUT ]; then break; fi
+    done
+    if [ $TRIES -gt $TIMEOUT ]; then echo "ERROR"; else echo "OK"; fi
 fi
 
 #frume.awk
