the code to enable statelite semantics on top of ramdisk is here: there's one new attribute called "rootfstype" for the osimage;
git-svn-id: https://svn.code.sf.net/p/xcat/code/xcat-core/trunk@8564 8638fb3e-16cb-4fca-ae20-7b5d299a9bcd

diff --git a/xCAT-server/share/xcat/netboot/rh/genimage b/xCAT-server/share/xcat/netboot/rh/genimage
--- a/xCAT-server/share/xcat/netboot/rh/genimage
+++ b/xCAT-server/share/xcat/netboot/rh/genimage
@@ -789,6 +789,7 @@ sub mkinitrd {
 	
 # add some functions
  	print $inifile <<EOS1; 	
+set -x
 NEWROOT="/sysroot"
 SHELL="/bin/sh"
 RWDIR=".statelite"
@@ -998,7 +999,6 @@ for i in `cat /proc/cmdline`; do
             rm -f \$FILENAME
           fi
         done
-        NFS=0
       fi
       if [ "nfs" == "`echo \$VALUE|awk -F: '{print \$1}'`" ]; then
         NFS=1
@@ -1012,16 +1012,19 @@ for i in `cat /proc/cmdline`; do
 	SERVER=`echo \$VALUE|awk -F: '{print \$1}'`
 	ROOTDIR=`echo \$VALUE|awk -F/ '{for(i=2;i<=NF;i++) printf "/%s",\$i}'`
    elif [ "\$KEY" == 'STATEMNT' ]; then
-	NFSROOT=1
+	STATELITE=1
 	VALUE=`echo \$i |awk -F= '{print \$2}'`
-	SNAPSHOTSERVER=`echo \$VALUE|awk -F: '{print \$1}'`
-	SNAPSHOTROOT=`echo \$VALUE|awk -F/ '{for(i=2;i<=NF;i++) printf "/%s",\$i}'`
-	# may be that there is not server and just a directory.
-	if [ -z \$SNAPSHOTROOT ]
-	then
-		 SNAPSHOTROOT=\$SNAPSHOTSERVER
-		SNAPSHOTSERVER=
-	fi
+    # the VALUE may be null
+    if [ ! -z \$VALUE ]; then
+	    SNAPSHOTSERVER=`echo \$VALUE|awk -F: '{print \$1}'`
+	    SNAPSHOTROOT=`echo \$VALUE|awk -F/ '{for(i=2;i<=NF;i++) printf "/%s",\$i}'`
+	    # may be that there is not server and just a directory.
+	    if [ -z \$SNAPSHOTROOT ]
+	    then
+		    SNAPSHOTROOT=\$SNAPSHOTSERVER
+		    SNAPSHOTSERVER=
+	    fi
+    fi
    fi
 done
 
@@ -1031,141 +1034,145 @@ fancydisplay
 
 echo 0 > /proc/sys/vm/zone_reclaim_mode #Avoid kernel bug
 
-# NFSROOT code here:
-if [ "\$NFSROOT" = "1" ]; then
-	echo Setting up Statelite
-	# for loop back mounting capability!
-	mknod /dev/loop0 b 7 0
-	mkdir -p \$NEWROOT
- 	MAXTRIES=5
-	ITER=0
-	ME=`hostname`
-	while ! mount.nfs \${SERVER}:\${ROOTDIR}/rootimg \$NEWROOT -r -n -o nolock,rsize=32768,tcp,nfsvers=3,timeo=14
-	do
-		ITER=\$(expr \$ITER + 1)
-		if [ "\$ITER" == "\$MAXTRIES" ]
-      		then
-				echo "You're dead.  rpower \$ME boot to play again."
-				echo "Possible problems:
-1.  This initrd wasn't created for statelite node?  rerun genimage with the -m statelite flag, then rerun 'nodeset \$ME statelite'
-2.  Is DNS set up?  Maybe that's why I can't mount \${SERVER}.
-3.  The nfs modules aren't set right in this initfs?"
-    
-			shell
-			exit
-		fi
-		echo -e "\${RED}Could not mount \$SERVER:\$ROOTDIR on \$NEWROOT \$RESET"
-		RS=`expr \$RANDOM % 30`
-		echo -e "Trying again in \$RS seconds"
-		sleep \$RS
-	done
-
-# now we need to mount the rest of the system.  This is the read/write portions
-#echo "Mounting Snapshot directories"
-
-	if [ ! -e "\$NEWROOT/\$RWDIR" ]
-	then
-		echo ""
-		echo -e "\${RED}Hmmm... this NFS root directory doesn't have a /\$RWDIR directory for me to mount a rw filesystem.  You'd better create it... \${NORMAL}"
-		echo "."
-		shell
-	fi
-
-	while [ ! -e "\$NEWROOT/etc/init.d/statelite" ]
-	do
-		echo ""
-		echo -e "\${RED}Hmmm... \$NEWROOT/etc/init.d/statelite doesn't exist.  Perhaps you didn't run liteimg for the current osimage"
-		echo ""
-		shell
-	done
-	grep '\\(shell\\)' /proc/cmdline >/dev/null && shell
-	mount -t tmpfs rw  -o mode=$permission \$NEWROOT/\$RWDIR
-	mkdir -p \$NEWROOT/\$RWDIR/tmpfs
-
-
-	# mount the SNAPSHOT directory here for persistent use.
-	if [ ! -z \$SNAPSHOTSERVER ]
-	then
-		mkdir -p \$NEWROOT/\$RWDIR/persistent
- 		MAXTRIES=5
-		ITER=0
-		while ! mount \$SNAPSHOTSERVER:\$SNAPSHOTROOT  \$NEWROOT/\$RWDIR/persistent -o nolock,rsize=32768,tcp,nfsvers=3,timeo=14
-		do
-			ITER=\$(expr \$ITER + 1)
-			if [ "\$ITER" == "\$MAXTRIES" ]
-      			then
-				echo "You're dead.  rpower \$ME boot to play again."
-				echo "Possible problems:
-1.  \$SNAPSHOTSERVER is not exporting \$SNAPSHOTROOT ?
-2.  Is DNS set up?  Maybe that's why I can't mount \$SNAPSHOTSERVER."
-				shell
-				exit
-			fi
-			echo -e "\${RED}Hmmm... Can't mount \$SNAPSHOTSERVER:\$SNAPSHOTROOT. \${NORMAL}"
-			RS=`expr \$RANDOM % 20`
-			echo -e "Trying again in \$RS seconds"
-			sleep \$RS	
-		done
-	fi
-
-	grep '\\(shell\\)' /proc/cmdline >/dev/null && shell
-
-	# have to preserve the initial DHCP request.  So we link it.
-
-	if [ ! -d \$NEWROOT/\$RWDIR/tmpfs/var/lib/dhclient ]
-	then
-		mkdir -p \$NEWROOT/\$RWDIR/tmpfs/var/lib/dhclient
-	fi
-	if [ ! -d \$NEWROOT/\$RWDIR/tmpfs/var/lib/dhcp ]
-	then
-		mkdir -p \$NEWROOT/\$RWDIR/tmpfs/var/lib/dhcp
-	fi
-
-	cp -fp /var/lib/dhclient/dhclient.leases \${NEWROOT}/\${RWDIR}/tmpfs/var/lib/dhclient/dhclient-\$IFACE.leases
-	cp -fp /var/lib/dhclient/dhclient.leases \${NEWROOT}/\${RWDIR}/tmpfs/var/lib/dhcp/dhclient-\$IFACE.leases
-
-
-	[ -e /etc/ntp.conf ] && mkdir -p \$NEWROOT/\$RWDIR/tmpfs/etc && cp /etc/ntp.conf \$NEWROOT/\$RWDIR/tmpfs/etc/ 
-
-	
-	[ -e /etc/ntp/step-kickers ] && mkdir -p \$NEWROOT/\$RWDIR/tmpfs/etc/ntp && cp /etc/ntp/step-kickers \$NEWROOT/\$RWDIR/tmpfs/etc/ntp 
-
-	
-	[ -e /etc/resolv.conf ] && mkdir -p \$NEWROOT/\$RWDIR/tmpfs/etc && cp /etc/resolv.conf \$NEWROOT/\$RWDIR/tmpfs/etc/ 
-
-	# now that everything is mounted, lets do this
-	# hmmm, apparently I'm checking this twice... so I'd better
-	# be really sure the file is there.
-	while [ ! -e \$NEWROOT/etc/init.d/statelite ]
-	do
-		echo "\$NEWROOT/etc/init.d/statelite does not exist in image!"
-		shell
+# STATELITE code here:
+if [ "\$STATELITE" = "1" ]; then
+    echo Setting up Statelite
+    # for loop back mouting capability!
+    mknod /dev/loop0 b 7 0
+    mkdir -p \$NEWROOT
+    MAXTRIES=5
+    ITER=0
+    ME=`hostname`
+    if [ "\$NFSROOT" = "1" ]; then
+        while ! mount.nfs \${SERVER}:\${ROOTDIR}/rootimg \$NEWROOT -r -n -o nolock,rsize=32768,tcp,nfsvers=3,timeo=14; do
+            ITER=\$(expr \$ITER + 1)
+            if [ "\$ITER" == "\$MAXTRIES" ]; then
+                echo "You are dead. rpower \$ME boot to play again."
+                echo "Possible problems:
+1. This initrd wasn't craeted for the statelite node?
+2. Is DNS set up? Maybe that's why I can't mount \${SERVER}.
+3. The nfs modules aren't set right in this initfs?"
+                shell
+                exit
+            fi
+            echo -e "\${RED}Could not mount \$SERVER:\$ROOTDIR on \$NEWROOT \$RESET"
+            RS=`expr \$RANDOM % 30`
+            echo -e "Trying again in \$RS seconds"
+            sleep \$RS
+        done
+    elif [ "\$NFS" = "1" ]; then
+        echo -e "\${RED}The \"imgurl=\" value should not be nfs-type if statelite mode is enabled \$RESET"
+        shell
         exit
-	done
+    else
+        # for statelite mode on top of the ramdisk
+EOMS
+    print $inifile "if [ -r /rootimg-statelite.gz ]; then\n";
+    print $inifile "echo Setting up RAM-root tmpfs.\n";
+    if ($rootlimit) {
+        print $inifile "    mount -o size=$rootlimit mode=755 -t tmpfs rootfs \$NEWROOT \n";
+    } else {
+        print $inifile "    mount -o mode=755 -t tmpfs rootfs \$NEWROOT\n";
+    }
+    print $inifile <<EOMS;
+            modprobe nfs
+            cd \$NEWROOT
+            echo -n "Extracting root file system:"
+            if [ -x /bin/cpio ]; then
+                gzip -cd /rootimg-statelite.gz |/bin/cpio -idum
+            else
+                gzip -cd /rootimg-statelite.gz |cpio -idum
+            fi
+            echo Done
+        else
+            echo -e "\${RED} Couldnot find rootimg-statelite.gz for statelite on top of ramdisk \$RESET"
+            shell
+            exit
+        fi
 
-	# do all the mounts:
-	\$NEWROOT/etc/init.d/statelite	
+    fi
+    # now we need to mount the rest of the system. 
+    if [ ! -e "\$NEWROOT/\$RWDIR" ]; then
+        echo ""
+        echo -e "\${RED}Hmmm... this NFS root directories doesn't have a /\$RWDIR directory for me to mount a rw filesystem. You'd better to create it... \${NORMAL}"
+        echo ""
+        shell
+        exit
+    fi
 
-	# give the debug shell just before we go if specified!
-	grep '\(shell\)' /proc/cmdline > /dev/null && shell
+    while [ ! -e "\$NEWROOT/etc/init.d/statelite" ]; do
+        echo ""
+        echo -e "\${RED}Hmmm... \$NEWROOT/etc/init.d/statelite doesn't exist. Perhaps you didn't run liteimg for the current osimage"
+        echo ""
+        shell
+        exit
+    done
 
-	echo 0x100 > /proc/sys/kernel/real-root-dev
-	export keep_old_ip=yes
-	export fastboot=yes
-	export READONLY=yes
-	grep '\\(shell\\)' /proc/cmdline >/dev/null && shell
-	mount -n --bind /dev /sysroot/dev
-	umount /sys
-	umount /proc
+    mount -t tmpfs rw -o mode=$permission \$NEWROOT/\$RWDIR
+    mkdir -p \$NEWROOT/\$RWDIR/tmpfs
 
-	if ! exec /sbin/switch_root -c /dev/console \$NEWROOT /sbin/init
-	then
-		echo ""
-		echo -e "\${RED}Couldn't switch_root.  Something must be wrong with NFS root image.\${RESET}"
-	#	mount -t proc proc /proc
-		shell
-	fi
-	exit
+    # mount the SNAPSHOT directory here for persistent use.
+    if [ ! -z \$SNAPSHOTSERVER ]; then
+        mkdir -p \$NEWROOT/\$RWDIR/persistent
+        MAXTRIES=5
+        ITER=0
+        while ! mount \$SNAPSHOTSERVER:\$SNAPSHOTROOT \$NEWROOT/\$RWDIR/persistent -o nolock,rsize=32768; do
+            ITER=\$(expr \$ITER + 1 )
+            if [ "\$ITER" == "\$MAXTRIES" ]; then
+                echo "You're dead. rpower \$ME boot to play again."
+                echo "Possible problems:
+1.  \$SNAPSHOTSERVER is not exporting \$SNAPSHOTROOT ?
+2.  IS DNS set up? Maybe that's why I can't mount \$SNAPSHOTSERVER.";
+                shell
+                exit
+            fi
+            echo -e "\${RED}Hmmm... Can't mount \$SNAPSHOTSERVER:\$SNAPSHOTROOT. \${NORMAL}"
+            RS=\$(expr \$RANDOM % 20 )
+            echo -e "Trying again in \$RS seconds"
+            sleep \$RS
+        done
+    fi
+
+    # have to preserve the initial DHCP request.
+    if [ ! -d \$NEWROOT/\$RWDIR/tmpfs/var/lib/dhclient ]; then
+        mkdir -p \$NEWROOT/\$RWDIR/tmpfs/var/lib/dhclient
+    fi
+
+    if [ ! -d \$NEWROOT/\$RWDIR/tmpfs/var/lib/dhcp ]; then
+        mkdir -p \$NEWROOT/\$RWDIR/tmpfs/var/lib/dhcp
+    fi
+
+    cp -fp /var/lib/dhclient/dhclient.leases \$NEWROOT/\$RWDIR/tmpfs/var/lib/dhclient/dhclient-\$IFACE.leases
+    cp -fp /var/lib/dhclient/dhclient.leases \$NEWROOT/\$RWDIR/tmpfs/var/lib/dhcp/dhclient-\$IFACE.leases
+
+    [ -e /etc/ntp.conf ] && mkdir -p \$NEWROOT/\$RWDIR/tmpfs/etc && cp /etc/ntp.conf \$NEWROOT/\$RWDIR/tmpfs/etc/
+    [ -e /etc/ntp/step-kickers ] && mkdir -p \$NEWROOT/\$RWDIR/tmpfs/etc/ntp && cp /etc/ntp/step-kickers \$NEWROOT/\$RWDIR/tmpfs/etc/ntp
+    [ -e /etc/resolv.conf ] && mkdir -p \$NEWROOT/\$RWDIR/tmpfs/etc && cp /etc/resolv.conf \$NEWROOT/\$RWDIR/tmpfs/etc/
+
+    while [ ! -e \$NEWROOT/etc/init.d/statelite ]; do
+        echo -e "\${RED} \$NEWROOT/etc/init.d/statelite doesn't exist in the osimge! \${NORMAL}"
+        shell
+    done
+
+    # do all the mounts
+    \$NEWROOT/etc/init.d/statelite
+
+    # give the debug shell just before we go if specified!
+    grep '\(shell\)' /proc/cmdline >/dev/null && shell
+
+    echo 0x100 > /proc/sys/kernel/real-root-dev
+    export keep_old_ip=yes
+    mount -n --bind /dev/ \$NEWROOT/dev
+
+    umount /sys
+    umount /proc
+
+    if ! exec /sbin/switch_root -c /dev/console \$NEWROOT /sbin/init; then
+        echo ""
+        echo -e "\${RED}Couldn't switch_root. Something must be wrong with the root image.\${RESET}"
+        shell
+    fi
+
 fi
 # END NFSROOT/Statelite code
 
@@ -1176,20 +1183,20 @@ if [ -r /rootimg.sfs ]; then
   mkdir -p /rw
   mount -t squashfs /rootimg.sfs /ro
   mount -t tmpfs rw /rw
-  mount -t aufs -o dirs=/rw:/ro mergedroot /sysroot
-  mkdir -p /sysroot/ro
-  mkdir -p /sysroot/rw
-  mount --move /ro /sysroot/ro
-  mount --move /rw /sysroot/rw
+  mount -t aufs -o dirs=/rw:/ro mergedroot \$NEWROOT
+  mkdir -p \$NEWROOT/ro
+  mkdir -p \$NEWROOT/rw
+  mount --move /ro \$NEWROOT/ro
+  mount --move /rw \$NEWROOT/rw
 EOMS
    print $inifile "elif [ -r /rootimg.gz ]; then\n";
    print $inifile "echo Setting up RAM-root tmpfs.\n";
    if ($rootlimit) {
-      print $inifile "  mount -o size=$rootlimit mode=755 -t tmpfs rootfs /sysroot\n";
+      print $inifile "  mount -o size=$rootlimit mode=755 -t tmpfs rootfs \$NEWROOT\n";
    } else {
-      print $inifile "  mount -o  mode=755 -t tmpfs rootfs /sysroot\n";
+      print $inifile "  mount -o  mode=755 -t tmpfs rootfs \$NEWROOT\n";
    }
-   print $inifile "  cd /sysroot\n";
+   print $inifile "  cd \$NEWROOT\n";
    print $inifile "  echo -n \"Extracting root filesystem:\"\n";
    print $inifile "  if [ -x /bin/cpio ]; then\n";
    print $inifile "  zcat /rootimg.gz |/bin/cpio -idum\n";
@@ -1220,11 +1227,11 @@ EOMS
    print $inifile "  exit\n";
    print $inifile "fi\n";
    print $inifile "cd /\n";
-   print $inifile "cp /var/lib/dhclient/dhclient.leases /sysroot/dev/.dhclient-\$IFACE.leases\n";
-   print $inifile "cp /var/lib/dhclient/dhclient.leases /sysroot/var/lib/dhclient/dhclient-\$IFACE.leases\n";
-   print $inifile 'if [ -z "$SNAPSHOTSERVER" ]; then cp /etc/resolv.conf /sysroot/etc/resolv.conf; fi'."\n";
-   print $inifile "mknod /sysroot/dev/console c 5 1\n";
-   print $inifile "exec switch_root -c /dev/console /sysroot /sbin/init\n";
+   print $inifile "cp /var/lib/dhclient/dhclient.leases \$NEWROOT/dev/.dhclient-\$IFACE.leases\n";
+   print $inifile "cp /var/lib/dhclient/dhclient.leases \$NEWROOT/var/lib/dhclient/dhclient-\$IFACE.leases\n";
+   print $inifile 'if [ -z "$SNAPSHOTSERVER" ]; then cp /etc/resolv.conf \$NEWROOT/etc/resolv.conf; fi'."\n";
+   print $inifile "mknod \$NEWROOT/dev/console c 5 1\n";
+   print $inifile "exec switch_root -c /dev/console \$NEWROOT /sbin/init\n";
    close($inifile);
 
    open($inifile,">"."/tmp/xcatinitrd.$$/bin/netstart");
@@ -1301,29 +1308,27 @@ EOMS
       }
    }
 
-	# Copy udev and network scripts into initrd for s390x
-	if ($arch eq "s390x") {
-		# udev
-		system("mkdir -p /tmp/xcatinitrd.$$/etc/udev");
-		system("cp -r $rootimg_dir/etc/udev/* /tmp/xcatinitrd.$$/etc/udev");
-		system("mkdir -p /tmp/xcatinitrd.$$/lib/udev");
-		system("cp -r $rootimg_dir/lib/udev/* /tmp/xcatinitrd.$$/lib/udev");
-		system("mkdir -p /tmp/xcatinitrd.$$/proc/self");
-		system("cp -r /proc/self/oom_adj /tmp/xcatinitrd.$$/proc/self");
-		
-		# Network related scripts
-		system("mkdir -p /tmp/xcatinitrd.$$/etc/sysconfig");
-		system("cp -r $rootimg_dir/etc/sysconfig/* /tmp/xcatinitrd.$$/etc/sysconfig");
-		system("mkdir -p /tmp/xcatinitrd.$$/sbin");
-		system("cp -r $rootimg_dir/sbin/* /tmp/xcatinitrd.$$/sbin");
-		system("mkdir -p /tmp/xcatinitrd.$$/lib/modules/$kernelver");
-		system("cp -r $rootimg_dir/lib/modules/$kernelver/modules.dep /tmp/xcatinitrd.$$/lib/modules/$kernelver/modules.dep");
-		system("mkdir -p /tmp/xcatinitrd.$$/etc/init.d");
-		system("cp -r $rootimg_dir/etc/init.d/* /tmp/xcatinitrd.$$/etc/init.d");
-		system("mkdir -p /tmp/xcatinitrd.$$/lib64");
-		system("cp -r $rootimg_dir/lib64/* /tmp/xcatinitrd.$$/lib64");
-		system("mkdir -p /tmp/xcatinitrd.$$/var/run/netreport");
-	}
+	# Copy udev and network scripts into initrd for s390x, which also works for other platforms
+	# udev
+	system("mkdir -p /tmp/xcatinitrd.$$/etc/udev");
+	system("cp -r $rootimg_dir/etc/udev/* /tmp/xcatinitrd.$$/etc/udev");
+	system("mkdir -p /tmp/xcatinitrd.$$/lib/udev");
+	system("cp -r $rootimg_dir/lib/udev/* /tmp/xcatinitrd.$$/lib/udev");
+	system("mkdir -p /tmp/xcatinitrd.$$/proc/self");
+	system("cp -r /proc/self/oom_adj /tmp/xcatinitrd.$$/proc/self");
+	
+	# Network related scripts
+	system("mkdir -p /tmp/xcatinitrd.$$/etc/sysconfig");
+	system("cp -r $rootimg_dir/etc/sysconfig/* /tmp/xcatinitrd.$$/etc/sysconfig");
+	system("mkdir -p /tmp/xcatinitrd.$$/sbin");
+	system("cp -r $rootimg_dir/sbin/* /tmp/xcatinitrd.$$/sbin");
+	system("mkdir -p /tmp/xcatinitrd.$$/lib/modules/$kernelver");
+	system("cp -r $rootimg_dir/lib/modules/$kernelver/modules.dep /tmp/xcatinitrd.$$/lib/modules/$kernelver/modules.dep");
+	system("mkdir -p /tmp/xcatinitrd.$$/etc/init.d");
+	system("cp -r $rootimg_dir/etc/init.d/* /tmp/xcatinitrd.$$/etc/init.d");
+	system("mkdir -p /tmp/xcatinitrd.$$/lib64");
+	system("cp -r $rootimg_dir/lib64/* /tmp/xcatinitrd.$$/lib64");
+	system("mkdir -p /tmp/xcatinitrd.$$/var/run/netreport");
 	
    #copy("$rootimg_dir/lib/modules/*d","/tmp/xcatinitrd.$$/$_");
    system("cd /tmp/xcatinitrd.$$;find .|cpio -H newc -o|gzip -9 -c - > $destdir/initrd-$mode.gz");
diff --git a/xCAT-server/share/xcat/netboot/sles/genimage b/xCAT-server/share/xcat/netboot/sles/genimage
--- a/xCAT-server/share/xcat/netboot/sles/genimage
+++ b/xCAT-server/share/xcat/netboot/sles/genimage
@@ -949,14 +949,17 @@ for i in `cat /proc/cmdline`; do
         SERVER=`echo \$VALUE|awk -F: '{print \$1}'`
         ROOTDIR=`echo \$VALUE|awk -F/ '{for(i=2;i<=NF;i++) printf "/%s",\$i}'`
    elif [ "\$KEY" == 'STATEMNT' ]; then
-        NFSROOT=1
+        STATELITE=1
         VALUE=`echo \$i |awk -F= '{print \$2}'`
-        SNAPSHOTSERVER=`echo \$VALUE|awk -F: '{print \$1}'`
-        SNAPSHOTROOT=`echo \$VALUE|awk -F/ '{for(i=2;i<=NF;i++) printf "/%s",\$i}'`
-        # may be that there is not server and just a directory.
-        if [ -z \$SNAPSHOTROOT ]; then
-            SNAPSHOTROOT=\$SNAPSHOTSERVER
-            SNAPSHOTSERVER=
+        # VALUE may be null
+        if [ ! -z \$VALUE ]; then
+            SNAPSHOTSERVER=`echo \$VALUE|awk -F: '{print \$1}'`
+            SNAPSHOTROOT=`echo \$VALUE|awk -F/ '{for(i=2;i<=NF;i++) printf "/%s",\$i}'`
+            # may be that there is not server and just a directory.
+            if [ -z \$SNAPSHOTROOT ]; then
+                SNAPSHOTROOT=\$SNAPSHOTSERVER
+                SNAPSHOTSERVER=
+            fi
         fi
     fi
 done
@@ -964,35 +967,57 @@ done
 # show xCAT logo
 fancydisplay
 
-# begin NFSROOT/Statelite code
-if [ "\$NFSROOT" = "1" ]; then
+# Statelite code is here
+if [ "\$STATELITE" = "1" ]; then
     echo Setting up Statelite
-    # for loop back mounting capability!
     mknod /dev/loop0 b 7 0
     mkdir -p \$NEWROOT
     MAXTRIES=15
     ITER=0
     ME=`hostname`
-    while ! mount.nfs \${SERVER}:\${ROOTDIR}/rootimg \$NEWROOT -r -n -o nolock,rsize=32768,tcp,nfsvers=3,timeo=14
-    do
-        ITER=\$(expr \$ITER + 1)
-        if [ "\$ITER" == "\$MAXTRIES" ]
-        then
-            echo "You're dead.  rpower \$ME boot to play again."
-            echo "Possible problems:
-1.  This initrd wasn't created for statelite node?  rerun genimage with the -m statelite flag, then rerun 'nodeset \$ME statelite'
-2.  Is DNS set up?  Maybe that's why I can't mount \${SERVER}.
-3.  The nfs modules aren't set right in this initfs?"
-    
-            shell
-            exit
-        fi
-        echo -e "\${RED}Could not mount \$SERVER:\$ROOTDIR on \$NEWROOT \$RESET"
-        RS=`expr \$RANDOM % 30`
-        echo -e "Trying again in \$RS seconds"
-        sleep \$RS
-    done
+    if [ "\$NFSROOT" = "1" ]; then
+        while ! mount.nfs \${SERVER}:\${ROOTDIR}/rootimg \$NEWROOT -r -n -o nolock,rsize=32768,tcp,nfsvers=3,timeo=14; do
+            ITER=\$(expr \$ITER + 1)
+            if [ "\$ITER" = "\$MAXTRIES" ]; then
+                echo "You're dead. rpower \$ME boot to play again."
+                echo "Possible problems:
+1.  This initrd wan't created for the statelite node? 
+2.  IS DNS set up? Maybe that's why I can't mount \${SERVER}.
+3.  The nfs modules aren't set right in this initial ramdisk?"
+                shell
+                exit
+            fi
+            echo -e "\${RED}Couldn't mount \$SERVER:\$ROOTDIR on \$NEWROOT \$RESET"
+            RS=\$(expr \$RANDOM % 30)
+            echo -e "Trying again in \$RS seconds"
+            sleep \$RS
+        done
+    else
+        # for statelite mode on top of the ramdisk
+EOMS
+    print $inifile "if [ -r /rootimg-statelite.gz ]; then \n";
+    print $inifile "echo Setting up RAM-root tmpfs.\n";
+    if ($rootlimit) {
+        print $inifile "    mount -o size=$rootlimit mode=755 -t tmpfs rootfs \$NEWROOT \n";
+    } else {
+        print $inifile "    mount -o mode=755 -t tmpfs rootfs \$NEWROOT \n";
+    }
 
+    print $inifile <<EOMS;
+        cd \$NEWROOT
+        echo -n "Extracting root file system:"
+        if [ -x /bin/cpio ]; then
+            gzip -cd /rootimg-statelite.gz | /bin/cpio -idum
+        else
+            gzip -cd /rootimg-statelite.gz | cpio -idum
+        fi
+        echo "Done"
+    else
+        echo -e "\${RED} Couldn't find rootimg-statelite.gz for statelite semantics on top of ramdisk \${RESET}"
+        shell
+        exit
+    fi
+fi
 # now we need to mount the rest of the system.  This is the read/write portions
 #echo "Mounting Snapshot directories"
     if [ ! -e "\$NEWROOT/\$RWDIR" ]
@@ -1111,9 +1136,9 @@ EOMS
    print $inifile "elif [ -r /rootimg.gz ]; then\n";
    print $inifile "echo Setting up RAM-root tmpfs.\n";
    if ($rootlimit) {
-      print $inifile "  mount -o size=$rootlimit  mode=755 -t tmpfs rootfs /sysroot\n";
+      print $inifile "  mount -o size=$rootlimit  mode=755 -t tmpfs rootfs \$NEWROOT\n";
    } else {
-      print $inifile "  mount -o  mode=755 -t tmpfs rootfs /sysroot\n";
+      print $inifile "  mount -o  mode=755 -t tmpfs rootfs \$NEWROOT\n";
    }
    print $inifile "  cd /sysroot\n";
    print $inifile "  echo -n \"Extracting root filesystem:\"\n";
@@ -1142,12 +1167,12 @@ EOMS
    print $inifile "  exit\n";
    print $inifile "fi\n";
    print $inifile "cd /\n";
-   print $inifile "mkdir /sysroot/var/lib/dhcpcd/\n";	#neccessary for SLES11, not sure for SLES10
-   print $inifile "cp /var/lib/dhcpcd/* /sysroot/var/lib/dhcpcd/\n";
-   print $inifile "cp /etc/resolv.conf /sysroot/etc/\n";
-   print $inifile "cp /etc/HOSTNAME /sysroot/etc/\n";
-   print $inifile "mknod /sysroot/dev/console c 5 1\n";
-   print $inifile "exec /lib/mkinitrd/bin/run-init -c /dev/console /sysroot /sbin/init\n";
+   print $inifile "mkdir \$NEWROOT/var/lib/dhcpcd/\n";	#neccessary for SLES11, not sure for SLES10
+   print $inifile "cp /var/lib/dhcpcd/* \$NEWROOT/var/lib/dhcpcd/\n";
+   print $inifile "cp /etc/resolv.conf \$NEWROOT/etc/\n";
+   print $inifile "cp /etc/HOSTNAME \$NEWROOT/etc/\n";
+   print $inifile "mknod \$NEWROOT/dev/console c 5 1\n";
+   print $inifile "exec /lib/mkinitrd/bin/run-init -c /dev/console \$NEWROOT /sbin/init\n";
    close($inifile);
    open($inifile,">"."/tmp/xcatinitrd.$$/bin/netstart");
    print $inifile "#!/bin/bash \n";
@@ -1175,7 +1200,7 @@ END
      }
    }
     if($mode eq "statelite") {
-        foreach ("sbin/ifconfig", "usr/bin/clear", "sbin/mount.nfs","sbin/umount.nfs","bin/hostname","usr/bin/egrep","bin/ln","bin/ls","usr/bin/dirname","usr/bin/expr","usr/bin/chroot","usr/bin/grep","bin/cpio","bin/sleep","bin/mount","bin/umount","sbin/dhcpcd","bin/bash","sbin/insmod","bin/mkdir","bin/mknod","sbin/ip","bin/cat","usr/bin/awk","usr/bin/wget","bin/cp","usr/bin/cpio","usr/bin/zcat","usr/bin/gzip","lib/mkinitrd/bin/run-init","usr/bin/uniq","usr/bin/sed","usr/bin/wc") {
+        foreach ("sbin/ifconfig", "usr/bin/clear", "sbin/mount.nfs","sbin/umount.nfs","bin/hostname","usr/bin/egrep","bin/ln","bin/ls","usr/bin/dirname","usr/bin/expr","usr/bin/chroot","usr/bin/grep","bin/cpio","bin/sleep","bin/mount","bin/umount","sbin/dhcpcd","bin/bash","sbin/insmod","bin/mkdir","bin/mknod","sbin/ip","bin/cat","usr/bin/awk","usr/bin/wget","bin/cp","usr/bin/cpio","usr/bin/zcat","usr/bin/gzip","lib/mkinitrd/bin/run-init","usr/bin/uniq","usr/bin/sed","usr/bin/wc", "bin/sed") {
             getlibs($_); 
             push @filestoadd,$_;
         } 
