not try to give "Error" message when the return code of actual command is non-zero, instead, use the return code of the actual command as the return code of xcatchroot.
git-svn-id: https://svn.code.sf.net/p/xcat/code/xcat-core/branches/2.7@12196 8638fb3e-16cb-4fca-ae20-7b5d299a9bcd

diff --git a/xCAT-client/bin/xcatchroot b/xCAT-client/bin/xcatchroot
--- a/xCAT-client/bin/xcatchroot
+++ b/xCAT-client/bin/xcatchroot
@@ -266,12 +266,12 @@ else
 
 	echo "\n\n$msg\n\n"
 
-	if [ ${rc} -ne 0 ]
-	then 
-		error=1
-		echo "\nError: The chroot command failed for '$cmd_string'."
-		echo "Error: The return code from chroot was '${rc}'\n"
-	fi
+	#if [ ${rc} -ne 0 ]
+	#then 
+	#	error=1
+	#	echo "\nError: The chroot command failed for '$cmd_string'."
+	#	echo "Error: The return code from chroot was '${rc}'\n"
+	#fi
 
 
 	# sensitive process has completed
@@ -289,8 +289,9 @@ fi
 /usr/bin/rm $location/xcatchrootscript
 
 # all done
-if [ $error -eq 1 ]
-then
-    exit 1
-fi
-exit 0
+#if [ $error -eq 1 ]
+#then
+#    exit 1
+#fi
+#exit 0
+exit ${rc}
