[go-xcat] Revise debug log, in order to make debugging go-xcat and bug reporting easier.

diff --git a/xCAT-server/share/xcat/tools/go-xcat b/xCAT-server/share/xcat/tools/go-xcat
--- a/xCAT-server/share/xcat/tools/go-xcat
+++ b/xCAT-server/share/xcat/tools/go-xcat
@@ -295,8 +295,10 @@ function internal_cleanup()
 #
 function custom_setup()
 {
-	check_exec_or_exit awk cat comm grep printf sleep tee
+	check_exec_or_exit awk cat comm grep printf sleep
 	check_root_or_exit
+
+	debug_log_setup
 }
 
 #
@@ -304,7 +306,7 @@ function custom_setup()
 #
 function custom_cleanup()
 {
-	:
+	debug_log_cleanup
 }
 
 #
@@ -317,6 +319,100 @@ function cleanup_n_exec()
 	internal_cleanup
 
 	exec "$@"
+}
+
+function debug_log_setup()
+{
+	local script="${0##*/}"
+
+	GO_XCAT_DEBUG_LOG="${TMP_DIR}/go-xcat.log"
+	GO_XCAT_LOG="/tmp/go-xcat.log"
+	# Global debug log file descriptor
+	: >"${GO_XCAT_DEBUG_LOG}"
+	ln -f "${GO_XCAT_DEBUG_LOG}" "${GO_XCAT_LOG}"
+
+	# Log all the command line arguments
+	{
+		echo "    ."
+		echo "      ."
+		echo "  . :."
+		echo "   .:"
+		echo "    ::."
+		echo "  :.::"
+		echo "  ::::."
+		echo "  :::::"
+		echo "  :::::"
+		echo "  :::::"
+		echo "  :::::"
+		echo "  :::::"
+		echo "..:::::.."
+		echo " ':::::'"
+		echo "   ':'"
+		echo -n "|->"
+		printf " %q" "${script}" "${BASH_ARGV[@]}"
+		echo
+		echo
+	} > >(debug_logger debug)
+}
+
+function debug_log_cleanup()
+{
+	local rc="$?"
+	local script="${0##*/}"
+
+	if [[ -n "${GO_XCAT_DEBUG_LOG}" && -n "${GO_XCAT_LOG}" ]]
+	then
+	    {
+			printf "\n|-> %-24s ... exited with %s\n" "${script}" "${rc}"
+			echo "     ......"
+			echo "     :::::"
+			echo "     ::::::."
+			echo "     ' ':::::."
+			echo "         ':::::."
+			echo "           '::"
+			echo "             '"
+		} > >(debug_logger debug)
+		[[ "${rc}" -eq "0" ]] && rm -f "${GO_XCAT_LOG}"
+	fi
+}
+
+function debug_logger()
+{
+	local level="$1"
+
+	while read -r
+	do
+		case "${level}" in
+		"debug")
+			;;
+		*)
+			echo "${REPLY}"
+			;;
+		esac
+		echo "${REPLY}" >&2
+	done 2>>"${GO_XCAT_DEBUG_LOG}"
+}
+
+function debug_trace()
+{
+	local rc="$?"
+
+	# Log the function name and all the command line arguments
+	{
+		echo
+		echo -n ".->"
+		printf " %q" "$@"
+		echo
+		echo "'========"
+	} > >(debug_logger debug)
+
+	"$@" > >(debug_logger) 2>&1
+	rc="$?"
+
+	printf ".========\n'-> %-24s ... returned with %s\n" "${1}" "${rc}" \
+		> >(debug_logger debug)
+
+	return "${rc}"
 }
 
 internal_setup
@@ -1440,12 +1536,55 @@ function list_xcat_packages()
 		42< <(check_repo_version "${GO_XCAT_DEP_PACKAGE_LIST[@]}")
 }
 
+#
+# ask_to_continue       Ask to continue
+#
+#	Exits (not returns) if get negative reply from end user.
+#   This function is intend to read from STDIN.
+#
+#       $1  -y
+#       $2  Prompt
+#
+function ask_to_continue()
+{
+	[[ "$1" = "-y" ]] && return 0
+	shift
+	local prompt="$1"
+
+	echo
+	echo "${prompt}"
+	echo > >(debug_logger debug)
+	echo ".-> ${prompt}" > >(debug_logger debug)
+	while :
+	do
+		read -r -p "Continue? [y/n] "
+		echo "'-> Continue? [y/n]          ... ${REPLY}" > >(debug_logger debug)
+		case "${REPLY}" in
+		"Y"*|"y"*)
+			break
+			;;
+		"N"*|"n"*)
+			echo "Good-bye!"
+			exit 0
+			;;
+		*)
+			echo "Invalid response!"
+			;;
+		esac
+	done
+
+	return 0
+}
+
 # Test case 000
 # Check if all the xcat-core packages are on the same version
 function test_case_000_version()
 {
 	local ver=""
 	local -i ret=0
+
+	list_xcat_packages
+
 	while read -r
 	do
 		[[ "${REPLY}" = "(not installed)" ]] && continue
@@ -1453,6 +1592,7 @@ function test_case_000_version()
 		[[ "${ver}" = "${REPLY%%-*}" ]]
 		(( ret += $? ))
 	done < <(check_package_version "${GO_XCAT_CORE_PACKAGE_LIST[@]}")
+
 	return "${ret}"
 }
 
@@ -1462,17 +1602,13 @@ function test_case_001_xcatd()
 {
 	local f=""
 	local -i ret=0
-	for f in /var/run/xcat/{main,install,udp}service.pid
+
+	for f in /var/run/xcat{d,/{main,udp,install,cmdlog}service}.pid
 	do
 		kill -0 "$(<"${f}")"
 		(( ret += $? ))
 	done
-	for f in /var/run/xcat/cmdlogservice.pid
-	do
-		[[ -f "${f}" ]] || continue
-		kill -0 "$(<"${f}")"
-		(( ret += $? ))
-	done
+
 	return "${ret}"
 }
 
@@ -1483,32 +1619,24 @@ function test_case_002_lsdef()
 	(source /etc/profile.d/xcat.sh && lsdef)
 }
 
-# Perform basic smoke test
-function perform_smoke_test()
+# Perform basic smoke tests
+function perform_smoke_tests()
 {
 	local test_case=""
 	local -i ret=0
+
 	for test_case in $(compgen -A function "test_case_")
 	do
-		"${test_case}" >"${TMP_DIR}/${test_case}.stdout" \
-			2>"${TMP_DIR}/${test_case}.stderr"
+		debug_trace "${test_case}"
 		ret="$?"
-		if [[ "${ret}" -ne "0" || -s "${TMP_DIR}/${test_case}.stderr" ]]
+
+		if [[ "${ret}" -ne "0" ]]
 		then
-			# Something went wrong
-			echo "-- 8< -- -- -- -- -- -- -- -- -- -- -- -- -- -- --"
-			echo "==== ${test_case} failed with exit code ${ret} ===="
-			echo "-- 8< ${test_case} stdout -- --"
-			while read -r ; do echo "${REPLY}" ; done \
-				<"${TMP_DIR}/${test_case}.stdout"
-			echo "-- 8< ${test_case} stderr -- --"
-			while read -r ; do echo "${REPLY}" ; done \
-				<"${TMP_DIR}/${test_case}.stderr"
-			echo "-- 8< -- -- -- -- -- -- -- -- -- -- -- -- -- -- --"
-			# skip all the remain test cases
 			return "${ret}"
-		fi >&2
+		fi
 	done
+
+	echo
 	echo "It seems everything went well. :)"
 	return 0
 }
@@ -1628,7 +1756,7 @@ case "${GO_XCAT_ACTION}" in
 "check"|"install"|"update")
 	;;
 "smoke-test")
-	perform_smoke_test
+	perform_smoke_tests
 	exit "$?"
 	;;
 "")
@@ -1644,8 +1772,7 @@ esac
 GO_XCAT_OS="$(check_os)"
 GO_XCAT_ARCH="$(check_arch)"
 
-while read -r ; do echo "${REPLY}" ; echo "${REPLY}" >&2
-	done 2>"${TMP_DIR}/go-xcat.log.000" <<EOF
+debug_logger <<EOF
 Operating system:   ${GO_XCAT_OS}
 Architecture:       ${GO_XCAT_ARCH}
 EOF
@@ -1669,8 +1796,7 @@ esac
 GO_XCAT_LINUX_DISTRO="$(check_linux_distro)"
 GO_XCAT_LINUX_VERSION="$(check_linux_version)"
 
-while read -r ; do echo "${REPLY}" ; echo "${REPLY}" >&2
-	done 2>"${TMP_DIR}/go-xcat.log.001" <<EOF
+debug_logger <<EOF
 Linux Distribution: ${GO_XCAT_LINUX_DISTRO}
 Version:            ${GO_XCAT_LINUX_VERSION}
 EOF
@@ -1683,18 +1809,29 @@ case "${GO_XCAT_LINUX_DISTRO}" in
 	;;
 esac
 
+debug_logger debug <<EOF
+
+Host Name:          ${HOSTNAME%%.*}
+Bash Version:       ${BASH_VERSION}
+EOF
+printf "%-19s %s\n\n" "${0##*/} Version:" "$(version)" > >(debug_logger >/dev/null)
+
 echo
 echo -n "Reading repositories "
 show_progress_meters
-ERR_MSG="$({
-	if add_xcat_core_repo -y "${GO_XCAT_CORE_URL}" "${GO_XCAT_VERSION}"
+ERR_MSG="$(
+{
+	echo
+	if debug_trace add_xcat_core_repo -y \
+		"${GO_XCAT_CORE_URL}" "${GO_XCAT_VERSION}"
 	then
-		if add_xcat_dep_repo -y "${GO_XCAT_DEP_URL}" "${GO_XCAT_VERSION}"
+		if debug_trace add_xcat_dep_repo -y \
+			"${GO_XCAT_DEP_URL}" "${GO_XCAT_VERSION}"
 		then
-			update_repo && exit 0
-			remove_repo "xcat-dep"
+			debug_trace update_repo && exit 0
+			debug_trace remove_repo "xcat-dep"
 		fi
-		remove_repo "xcat-core"
+		debug_trace remove_repo "xcat-core"
 	fi
 	exit 1
 } 2>&1)"
@@ -1718,9 +1855,10 @@ case "${GO_XCAT_ACTION}" in
 	then
 		echo
 		echo "xCAT is going to be ${GO_XCAT_ACTION/%e/}ed."
-		while true; do
-
+		while :
+		do
 			read -r -p "Continue? [y/n] "
+			echo "+> Continue? [y/n]          ... ${REPLY}" > >(debug_logger)
 			case "${REPLY}" in
 			"Y"*|"y"*)
 				break	
@@ -1735,52 +1873,21 @@ case "${GO_XCAT_ACTION}" in
 			esac
 		done
 	fi
-	# Use `-y' here. Since the STDOUT is redirect to tee.
+	# Use `-y' here. Since the STDOUT is redirected.
 	# `yum' does not display the prompt message properly when
-	# working with tee.
-	"${GO_XCAT_INSTALLER}" -y \
-		> >(tee "${TMP_DIR}/${GO_XCAT_INSTALLER}.stdout") \
-		2> >(tee "${TMP_DIR}/${GO_XCAT_INSTALLER}.stderr" >&2)
+	# working with redirected I/O.
+	debug_trace "${GO_XCAT_INSTALLER}" -y
 	RET="$?"
-	{
-		# Creating logs
-		echo "-- 8< -- -- -- -- -- -- -- -- -- -- -- -- -- -- --"
-		echo "==== ${GO_XCAT_INSTALLER} exited with exit code ${RET} ===="
-		echo "-- 8< ${GO_XCAT_INSTALLER} stdout -- --"
-		while read -r ; do echo "${REPLY}" ; done \
-			<"${TMP_DIR}/${GO_XCAT_INSTALLER}.stdout"
-		echo "-- 8< ${GO_XCAT_INSTALLER} stderr -- --"
-		while read -r ; do echo "${REPLY}" ; done \
-			<"${TMP_DIR}/${GO_XCAT_INSTALLER}.stderr"
-		echo "-- 8< -- -- -- -- -- -- -- -- -- -- -- -- -- -- --"
-	} >"${TMP_DIR}/go-xcat.log.005"
-	if [[ "${RET}" -eq "0" && ! -s "${TMP_DIR}/${GO_XCAT_INSTALLER}.stderr" ]]
+	if [[ "${RET}" -eq "0" ]]
 	then
 		# xCAT has been installed and so far so good
-		perform_smoke_test >"${TMP_DIR}/perform_smoke_test.stdout" \
-			2>"${TMP_DIR}/perform_smoke_test.stderr"
+		perform_smoke_tests >/dev/null 2>&1
 		RET="$?"
-		if [[ "${RET}" -ne "0" || -s "${TMP_DIR}/perform_smoke_test.stderr" ]]
-		then
-			# Smoke test failed
-			echo "-- 8< -- -- -- -- vv -- -- -- vv -- -- -- -- 8< --"
-			echo "==== perform_smoke_test failed with exit code ${RET} ===="
-			echo "-- 8< perform_smoke_test stdout -- --"
-			while read -r ; do echo "${REPLY}" ; done \
-				<"${TMP_DIR}/perform_smoke_test.stdout"
-			echo "-- 8< perform_smoke_test stderr -- --"
-			while read -r ; do echo "${REPLY}" ; done \
-				<"${TMP_DIR}/perform_smoke_test.stderr"
-			echo "-- 8< -- -- -- -- ^^ -- -- -- ^^ -- -- -- -- 8< --"
-		fi
-	fi >"${TMP_DIR}/go-xcat.log.008"
+	fi
 
 	if [[ "${RET}" -ne "0" ]]
 	then
-		GO_XCAT_LOG="/tmp/go-xcat.log"
-		cat "${TMP_DIR}/go-xcat.log."* >"${GO_XCAT_LOG}" 2>/dev/null
-		while read -r ; do echo "${REPLY}" ; done >&2 <<-EOF
-
+		debug_logger <<-EOF
 
 		Boo-boo
 		=======
@@ -1796,7 +1903,7 @@ case "${GO_XCAT_ACTION}" in
 	case "${GO_XCAT_ACTION}" in
 	"install")
 		# Only print out this message on install
-		while read -r ; do echo "${REPLY}" ; done <<-EOF
+		debug_logger <<-EOF
 
 		xCAT has been installed!
 		========================
@@ -1812,7 +1919,7 @@ case "${GO_XCAT_ACTION}" in
 		EOF
 		;;
 	"update")
-		while read -r ; do echo "${REPLY}" ; done <<-EOF
+		debug_logger <<-EOF
 
 		xCAT has been successfully updated!
 		EOF
