enhance activate-mn

diff --git a/xCAT-server/share/xcat/hamn/activate-mn b/xCAT-server/share/xcat/hamn/activate-mn
--- a/xCAT-server/share/xcat/hamn/activate-mn
+++ b/xCAT-server/share/xcat/hamn/activate-mn
@@ -25,18 +25,19 @@
 # -----------------------------------------------------------------------------
 # 2011-12-08   JDW     1.0     Original
 # 2013-06-06   xCAT    1.1     Updated version to ship with xCAT
-
+# 2017-10-17   xCAT    2.13.8  Enhance 
 SHAREDVG=sharedvg # For AIX, shared volumn group name
-SHAREDFS="/install /etc/xcat ~/.xcat" # Shared file systems
-DB2DIR=/db2database # DB2 only, the db2 database directory
+DBDIR=/var/lib/pgsql # database directory
+SHAREDFS="/install /etc/xcat /root/.xcat" # Shared file systems
 USEDFM=no # if DFM is being used
 USENTP=no # if NTP is being used
 POWER775=no # Power 775 cluster
 USETEAL=no # if TEAL is being used
-CHANGEHOSTNAME=no # set the hostname to the virtual ip address hostname
-
-
-xcatdb=`XCATBYPASS=1 /opt/xcat/bin/lsxcatd -d | cut -f 2 -d "=" 2>/dev/null`
+USEMOUNT=yes # mounted  filesystems in the file /etc/fstab
+CHANGEHOSTNAME=yes # set the hostname to the virtual ip address hostname
+RESTARTDNS=yes # if yes, will execute "makedns -n"
+exit_code=0
+xcatdb=postgresql # support postgrel,DB2,mysql 
 
 usage()
 {
@@ -49,7 +50,25 @@ EOF
 runcmd()
 {
     echo "Running command: $@"
-    $@
+    a=0
+    while true
+    do
+        if [ $a -eq 5 ]; then
+            echo "$@ [Failed]"
+            exit_code=1
+            return 1
+        elif [ $a -gt 0 ]; then
+            sleep 3
+            echo "Retry $a ...... $@"
+        fi
+        $@
+        if [ $? -eq 0 ]; then
+            echo "$@ [Passed]"
+            return 0
+        else
+           a=$[$a+1]
+        fi
+    done
 }
 
 ################################################################################
@@ -133,15 +152,14 @@ then
     runcmd "varyonvg $SHAREDVG"
 fi
 
-for fs in $SHAREDFS
-do
-    runcmd "mount $fs"
-done
-
-#DB2 only
-if [ $xcatdb = "DB2" ]
+if [ $USEMOUNT = "yes" ]
 then
-    runcmd "mount $DB2DIR"
+    for fs in $SHAREDFS $DBDIR
+    do
+        runcmd "mount $fs"
+    done
+else
+    echo "Warning: share data $SHAREDFS $DBDIR should be mounted before."
 fi
 
 # Start NFS
@@ -174,14 +192,14 @@ then
     if [ $xcatdb = "DB2" ]
     then
         runcmd "su - xcatdb -c \"db2start\""
-    elif [ $xcatdb = "mysql" ]
+    elif [ $DATABASE = "mysql" ]
     then
         runcmd "startsrc -g mysql"
     fi
 else # Linux
     if [ $xcatdb != "SQLite" ]
     then
-        runcmd "service $xcatdb start 2>&1 1>/dev/null"
+        runcmd "service $xcatdb start"
     fi
 fi
     
@@ -230,6 +248,11 @@ then
 fi
 
 ##############################################################################
+#Re-make dns
+if [ $RESTARTDNS = "yes" ]
+then
+    runcmd "makedns -n"
+fi
 
 # Re-make DHCP definitions
 echo "Making upto date DHCP configuration file...."
@@ -281,5 +304,9 @@ fi
 
 echo ""
 echo ""
-echo "This machine is set to active management node successfully, enjoy..."
-exit 0
+if [ $exit_code -eq 0 ]; then
+    echo "This machine is set to active management node successfully, enjoy..."
+else
+    echo "This machine is set to active management node, but some service failed..."
+fi
+exit $exit_code
